### ISSUE TITLE
Can the install process be more clearly?

### ISSUE THREAD

**Issue by codetime2015** [ScaDS/dblp-parser#1]
For a new java student that don't know much about the opensource or github , the whole process is a bit simple and looking forward to your easy to understand.

**Comment by merando** [comment]
Thanks for reaching out and for your feedback! Could you be a bit more precise? If you have specific questions on the installation process I'd be happy to answer here and improve the readme.

Thanks in advance.

**Comment by codetime2015** [comment]
I try to learn the use of maven and gradle from Google.The grable build or install are all executed successfully. Then  I think I finish the first three steps. But limited by my knowledge. I am puzzled with the fourth step. I don't understand how could the java project without errors. And I also want to know a running example of this project.

Thank you very much.

# gradle build
>:compileJava UP-TO-DATE
:processResources NO-SOURCE
:classes UP-TO-DATE
:jar UP-TO-DATE
:assemble UP-TO-DATE
:compileTestJava NO-SOURCE
:processTestResources NO-SOURCE
:testClasses UP-TO-DATE
:test NO-SOURCE
:check UP-TO-DATE
:build UP-TO-DATE

BUILD SUCCESSFUL

# gradle install

:compileJava UP-TO-DATE
:processResources NO-SOURCE
:classes UP-TO-DATE
:jar UP-TO-DATE
:install

BUILD SUCCESSFUL

**Comment by merando** [comment]
After the third step the installation of my code in your local maven repository is done. 
You can now include it in your project dependencies. e.g. for gradle it might be necessary to include the following in your build.gradle:
```
repositories {
  mavenLocal()
}

compile group: 'org.dblp', name: 'dblp-parser', version: '0.1.0'
```

I have a running example of this one but didn't plan to release it on github since it is quiet specific. 
Even though I might think about it. However, even if I decide to I need at least to weeks to find the time for doing it, sry. I hope the code above helps?

How to implement the processor might become clear when having a look into the example folder with the [StatisticsProcessor](https://github.com/ScaDS/dblp-parser/blob/master/src/main/java/org/dblp/example/StatisticsProcessor.java)

**Comment by merando** [comment]
Closed, since no further obligations where add.
